name: Android (OpenGL)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: Get DLC
      run: ./get_dlc
    - name: Get Node.js
      run: git clone https://github.com/Kode/nodejs_bin.git --depth 1
    - name: Setup Node.js
      run: nodejs_bin/copysysbin.sh
    - name: Compile
      run: nodejs_bin/node make.js android -g opengl --kha . --from Tests/Empty --arch arm8 --compile
